CREATE TABLE IF NOT EXISTS journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  content TEXT NOT NULL
);

ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS sentiment TEXT,
  ADD COLUMN IF NOT EXISTS mood_lifter_content TEXT,
  ADD COLUMN IF NOT EXISTS word_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sentence_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mistake_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lexical_feedback JSONB,
  ADD COLUMN IF NOT EXISTS unique_words INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lexical_diversity FLOAT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS readability TEXT,
  ADD COLUMN IF NOT EXISTS writing_style TEXT,
  ADD COLUMN IF NOT EXISTS grammar_trend TEXT,
  ADD COLUMN IF NOT EXISTS vocabulary_trend TEXT,
  ADD COLUMN IF NOT EXISTS progress_summary TEXT,
  ADD COLUMN IF NOT EXISTS emotion_words TEXT[],
  ADD COLUMN IF NOT EXISTS repeated_words TEXT[],
  ADD COLUMN IF NOT EXISTS positive_word_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS negative_word_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS neutral_word_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS layer2_pragmatic JSONB,
  ADD COLUMN IF NOT EXISTS layer3_temporal JSONB,
  ADD COLUMN IF NOT EXISTS layer4_goal JSONB,
  ADD COLUMN IF NOT EXISTS layer5_action JSONB;

CREATE INDEX IF NOT EXISTS idx_journal_entries_created_at ON journal_entries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_l2 ON journal_entries USING GIN (layer2_pragmatic);
CREATE INDEX IF NOT EXISTS idx_l3 ON journal_entries USING GIN (layer3_temporal);