DROP TABLE IF EXISTS journal_entries;
CREATE TABLE journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  content TEXT NOT NULL,
  sentiment TEXT,
  mood_lifter_content TEXT,
  word_count INT DEFAULT 0,
  sentence_count INT DEFAULT 0,
  mistake_count INT DEFAULT 0,
  lexical_feedback JSONB,
  unique_words INT DEFAULT 0,
  lexical_diversity FLOAT DEFAULT 0,
  readability TEXT,
  writing_style TEXT,
  grammar_trend TEXT,
  vocabulary_trend TEXT,
  progress_summary TEXT,
  emotion_words TEXT[],
  repeated_words TEXT[],
  positive_word_count INT DEFAULT 0,
  negative_word_count INT DEFAULT 0,
  neutral_word_count INT DEFAULT 0,
  user_id UUID REFERENCES auth.users(id),
  layer2_pragmatic JSONB,
  layer3_temporal JSONB,
  layer4_goal JSONB,
  layer5_action JSONB
);
CREATE INDEX IF NOT EXISTS idx_journal_entries_created_at ON journal_entries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_l2 ON journal_entries USING GIN (layer2_pragmatic);
CREATE INDEX IF NOT EXISTS idx_l3 ON journal_entries USING GIN (layer3_temporal);